image: cr.git.imsweb.com/plone/buildout-configs/plone-testrunner:latest
stages:
- test


before_script:
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_PROJECT_PATH
  - echo "Activating Source"
  - source /plone5/instance/bin/activate
  - cp -a /plone5/instance/.credentials ~/
  - chmod 700 ~/.credentials
  - pip install python-ldap
  - echo "Install Successful"
  - echo "Running buildout"
  - buildout -c gitlab-ci.cfg
  - echo "buildout successful"

plone-tests:
  tags:
    - openshift
  stage: test
  script:
    - echo "running test on version:"
    - python setup.py --version
    - /builds/$CI_PROJECT_PATH/bin/test -v -s $CI_PROJECT_NAME

code-analysis:
  tags:
    - openshift
  stage: test
  script:
    - echo "running test on version:"
    - python setup.py --version
    - /builds/$CI_PROJECT_PATH/bin/code-analysis .